# Generated by Django 6.0.7 on 2026-07-23 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome_cidade', models.CharField(max_length=100, verbose_name='Nome da Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado (UF)')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'ordering': ['nome_cidade'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=150, verbose_name='Nome Completo')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereco')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone/Celular')),
                ('email', models.EmailField(blank=True, max_length=150, null=True, verbose_name='Email')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('contato', models.CharField(blank=True, max_length=150, null=True, verbose_name='Pessoa de Contato')),
                ('conexao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Conexao/Relacionamento')),
                ('valor_mensalidade', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Mensalidade Padrao (R$)')),
                ('dia_cobranca', models.IntegerField(blank=True, null=True, verbose_name='Dia Padrao para Cobranca (1-31)')),
                ('obs', models.TextField(blank=True, null=True, verbose_name='Observacoes')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='cadastros.cidade', verbose_name='Cidade')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
    ]
