# Generated by Django 6.0.7 on 2026-07-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='pix_agencia',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Agencia'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='pix_banco',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='pix_chave',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Chave PIX'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='pix_conta',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Conta'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='pix_tipo_conta',
            field=models.CharField(blank=True, choices=[('CC', 'Conta Corrente'), ('CP', 'Poupanca'), ('CI', 'Investimento')], max_length=20, null=True, verbose_name='Tipo de Conta'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='pix_titular',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Titular PIX'),
        ),
    ]
