# Generated by Django 6.0.7 on 2026-07-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_empresa_pix_agencia_empresa_pix_banco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='assinatura',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/', verbose_name='Imagem da Assinatura'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='responsavel',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Responsavel'),
        ),
    ]
