# Generated by Django 6.0.7 on 2026-07-23 23:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cobranca_uuid', models.CharField(blank=True, db_index=True, max_length=36, null=True, verbose_name='UUID da Cobranca')),
                ('numero_parcela', models.CharField(db_index=True, max_length=20, verbose_name='Numero da Parcela')),
                ('total_parcelas', models.IntegerField(verbose_name='Total de Parcelas')),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Parcela (R$)')),
                ('data_geracao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Geracao')),
                ('data_vencimento', models.DateField(db_index=True, verbose_name='Data de Vencimento')),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('LIQUIDADA', 'Liquidada'), ('CANCELADA', 'Cancelada')], db_index=True, default='ABERTA', max_length=10, verbose_name='Status')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data do Pagamento')),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Pago (R$)')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='cadastros.cliente', verbose_name='Cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Parcela',
                'verbose_name_plural': 'Parcelas',
                'ordering': ['data_vencimento'],
            },
        ),
    ]
