# Generated by Django 6.0.7 on 2026-07-24 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parcela',
            options={'managed': False, 'ordering': ['vencimento'], 'verbose_name': 'Parcela', 'verbose_name_plural': 'Parcelas'},
        ),
    ]
